/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg:      '#06060E',
        bg2:     '#08081A',
        text:    '#F2F0FF',
        text2:   'rgba(196,181,253,0.72)',
        muted:   'rgba(148,163,184,0.55)',
        violet:  '#8B5CF6',
        violet2: '#7C3AED',
        cyan:    '#22D3EE',
        indigo:  '#818CF8',
        pink:    '#EC4899',
        emerald: '#34D399',
        border:  'rgba(255,255,255,0.08)',
      },
      fontFamily: {
        sans:    ['Manrope', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        display: ['"Space Grotesk"', 'Manrope', 'system-ui', 'sans-serif'],
        mono:    ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      backgroundImage: {
        'brand-gradient': 'linear-gradient(135deg, #22D3EE 0%, #818CF8 50%, #A855F7 100%)',
        'hero-gradient':  'radial-gradient(ellipse 80% 50% at 50% -10%, rgba(124,58,237,0.25) 0%, transparent 80%)',
      },
      boxShadow: {
        'glow-violet': '0 0 60px -10px rgba(139,92,246,0.6)',
        'glow-cyan':   '0 0 60px -10px rgba(34,211,238,0.4)',
        'glow-soft':   '0 30px 80px -20px rgba(124,58,237,0.5)',
        'card':        '0 4px 24px -4px rgba(0,0,0,0.4)',
        'card-hover':  '0 12px 40px -8px rgba(124,58,237,0.35)',
      },
      animation: {
        'float-slow':   'floatSlow 9s ease-in-out infinite',
        'float-slow2':  'floatSlow 12s ease-in-out infinite reverse',
        'pulse-dot':    'pulseDot 2.4s ease-in-out infinite',
        'shimmer':      'shimmer 2.5s linear infinite',
        'fade-up':      'fadeUp 0.6s ease both',
        'fade-in':      'fadeIn 0.5s ease both',
        'slide-right':  'slideRight 0.5s ease both',
        'ticker':       'ticker 30s linear infinite',
        'border-spin':  'borderSpin 4s linear infinite',
        'count-up':     'countUp 1s ease both',
        'glow-pulse':   'glowPulse 3s ease-in-out infinite',
        'marquee':      'marquee 38s linear infinite',
        'aurora':       'aurora 18s ease-in-out infinite',
        'shine':        'shine 6s ease-in-out infinite',
        // Redesign v2 (Claude Design)
        'sf-curtain-l':  'sfCurtainL 2.2s cubic-bezier(0.76,0,0.24,1) forwards',
        'sf-curtain-r':  'sfCurtainR 2.2s cubic-bezier(0.76,0,0.24,1) forwards',
        'sf-intro-mark': 'sfIntroMark 2.2s ease forwards',
        'sf-intro-off':  'sfIntroOff 2.3s linear forwards',
        'sf-spin':       'sfSpin 1s linear infinite',
        'sf-grain':      'sfGrain 1.1s steps(4) infinite',
        'sf-sweep':      'sfSweep 3.4s ease-in-out infinite',
        'sf-scan':       'sfScan 4.5s linear infinite',
        'sf-glow':       'sfGlow 6s ease-in-out infinite',
        'sf-beam':       'sfBeam 5s ease-in-out infinite',
        'sf-ring':       'sfRing 4s ease-out infinite',
        'sf-rise':       'sfRise 1.1s cubic-bezier(0.16,1,0.3,1) both',
      },
      keyframes: {
        floatSlow: {
          '0%,100%': { transform: 'translateY(0) scale(1)' },
          '50%':     { transform: 'translateY(-18px) scale(1.02)' },
        },
        pulseDot: {
          '0%,100%': { opacity: '1', transform: 'scale(1)' },
          '50%':     { opacity: '0.4', transform: 'scale(0.8)' },
        },
        shimmer: {
          '0%':   { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        fadeUp: {
          from: { opacity: '0', transform: 'translateY(24px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to:   { opacity: '1' },
        },
        slideRight: {
          from: { opacity: '0', transform: 'translateX(-20px)' },
          to:   { opacity: '1', transform: 'translateX(0)' },
        },
        ticker: {
          '0%':   { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        borderSpin: {
          '0%':   { backgroundPosition: '0% 50%' },
          '50%':  { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
        glowPulse: {
          '0%,100%': { opacity: '0.6' },
          '50%':     { opacity: '1' },
        },
        marquee: {
          '0%':   { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        aurora: {
          '0%,100%': { transform: 'translate(0,0) scale(1)',        opacity: '0.55' },
          '33%':     { transform: 'translate(4%,-3%) scale(1.08)',  opacity: '0.75' },
          '66%':     { transform: 'translate(-3%,4%) scale(0.96)',  opacity: '0.6' },
        },
        shine: {
          '0%,100%': { backgroundPosition: '0% 50%' },
          '50%':     { backgroundPosition: '100% 50%' },
        },
        // Redesign v2 (Claude Design)
        sfCurtainL:  { '0%,40%': { transform: 'translateX(0)' }, '100%': { transform: 'translateX(-101%)' } },
        sfCurtainR:  { '0%,40%': { transform: 'translateX(0)' }, '100%': { transform: 'translateX(101%)' } },
        sfIntroMark: { '0%': { opacity: '0', transform: 'scale(.82)' }, '16%,32%': { opacity: '1', transform: 'scale(1)' }, '46%,100%': { opacity: '0', transform: 'scale(1.1)' } },
        sfIntroOff:  { '0%,99%': { visibility: 'visible' }, '100%': { visibility: 'hidden' } },
        sfSpin:      { to: { transform: 'rotate(360deg)' } },
        sfGrain:     { '0%,100%': { transform: 'translate(0,0)' }, '20%': { transform: 'translate(-2%,1%)' }, '40%': { transform: 'translate(1%,-2%)' }, '60%': { transform: 'translate(-1%,2%)' }, '80%': { transform: 'translate(2%,-1%)' } },
        sfSweep:     { '0%': { transform: 'translateX(-130%)' }, '100%': { transform: 'translateX(340%)' } },
        sfScan:      { '0%': { transform: 'translateY(-100%)' }, '100%': { transform: 'translateY(1500%)' } },
        sfGlow:      { '0%,100%': { opacity: '.35' }, '50%': { opacity: '.8' } },
        sfBeam:      { '0%,100%': { opacity: '.15' }, '50%': { opacity: '.5' } },
        sfRing:      { '0%': { transform: 'scale(.7)', opacity: '.55' }, '100%': { transform: 'scale(2.1)', opacity: '0' } },
        sfRise:      { from: { opacity: '0', transform: 'translateY(115%) rotate(2.5deg)' }, to: { opacity: '1', transform: 'translateY(0) rotate(0)' } },
      },
    },
  },
  plugins: [],
}
